# AllowHopper/AllowChest is currently not working.
# DisplayShopAddon made by bugzigus
# An expansion to DisplayShops by XZot1K
Shops:
  MaxAmount: 5
  AllowHopper: true
  AllowChest: true
Help:
  Enabled: true