name: DisplayShopAddon
version: 1.6.2
description: Addon to the DisplayShop Plugin
author: bugzigus
depend: [DisplayShops]
main: me.bugzigus.DisplayShopAddon.DisplayShopAddon
commands:
  dsa:
    aliases: displayshopaddon
    description: Base Command for the plugin
    usage: /dsa [action] [other-terms]

permissions:
  displayshopaddon.*:
    description: Gives access to all Addon permissions
    children:
      displayshopaddon.link: true
      displayshopaddon.read: true
      displayshopaddon.unlink: true
      displayshopaddon.help: true
  displayshopaddon.link:
    description: Allows you to link shops
    default: true
  displayshopaddon.help:
    description: Help command permission
    default: true
  displayshopaddon.unlink:
    description: Allows you to unlink a shop
    default: true
  displayshopaddon.read:
    description: Dev Command no need to use
    default: op