name: DisplayShopAddon
version: 1.0.0
author: bugzigus
main: me.bugzigus.DisplayShopAddon.DisplayShopAddon
commands:
  linkshop:
    description: Used to link a chest to a chest shop
    usage: linkshop
  readconfig:
    description: Used to link a chest to a chest shop
    usage: linkshop
  unlinkshop:
    description: Used to unlink chest
    usage: unlinkshop